name: reportnic
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.0-55.0.dev


#Dependencias de la Aplicacion

dependencies:
  flutter:
    sdk: flutter  # Framework principal de Flutter.
    
  cupertino_icons: ^1.0.8  # Paquete de iconos de estilo iOS (Cupertino) para Flutter.

  firebase_core: ^3.4.0  # Integración principal de Firebase para inicializar los servicios en la app.

  firebase_auth: 5.2.0  # Maneja la autenticación de usuarios usando Firebase (email, Google, Facebook, etc.).

  cloud_firestore: ^5.2.0  # Base de datos en tiempo real basada en la nube para almacenar y sincronizar datos de la app.

  email_validator: ^2.0.0  # Valida direcciones de correo electrónico para asegurar que tengan un formato correcto.

  wave: ^0.2.2  # Crea animaciones de ondas para elementos visuales, generalmente usado en pantallas de bienvenida o interfaces atractivas.

  smooth_page_indicator: ^1.2.0+3  # Agrega indicadores visuales de paginación suaves, útiles para carruseles o tutoriales.

  http: ^1.2.2  # Cliente HTTP para realizar peticiones REST a servidores, útil para consumir APIs.

  provider: ^6.1.2  # Gestión del estado de la app de forma eficiente, permite notificar a los widgets cuando hay cambios.

  avatar_glow: ^3.0.1  # Añade un efecto de resplandor alrededor de un avatar o cualquier widget, útil para resaltar un elemento visual.

  voice_to_text: ^1.0.3  # Convierte voz a texto utilizando el micrófono del dispositivo.

  intl: ^0.19.0  # Proporciona utilidades para la internacionalización y localización, incluyendo el manejo de fechas, formatos de números, etc.

  shared_preferences: ^2.3.2  # Permite almacenar datos simples y persistentes como preferencias del usuario (por ejemplo, configuraciones).

  mapbox_maps_flutter: ^2.2.1  # Integración con Mapbox para mostrar mapas interactivos en la aplicación.

  geolocator: ^13.0.1  # Permite obtener la ubicación actual del dispositivo, ideal para funcionalidades basadas en GPS.

  permission_handler: ^11.3.1  # Maneja las solicitudes y verificaciones de permisos (como acceso a ubicación, cámara, micrófono, etc.).

  flutter_background: ^1.3.0+1  # Permite que la aplicación ejecute tareas en segundo plano cuando la app no está activa.

  encrypt: ^5.0.3  # Proporciona métodos de cifrado para asegurar la información, ideal para manejar datos sensibles.

  crypto: ^3.0.5  # Ofrece implementaciones criptográficas como hashing (SHA, MD5), firmas, cifrado, etc.

  tuple: ^2.0.2  # Paquete que permite manejar tuplas (estructuras de datos que agrupan múltiples valores) en Flutter.




dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.0


flutter_icons:
image_path: "assets/img/icon_app.png"
android: true
ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
   

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package


  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-VariableFont_wght.ttf
          weight: 700



  assets:
    - assets/img/logo_blanco.png
    - assets/img/logo_azul.png
    - assets/img/logo_blackout.png
    - assets/img/logo_amarillo.png
    - assets/img/ambulance_marker64px.png
    - assets/img/hospital_marker.png
    - assets/img/icon_app.png


