// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB07sR2b1NMI0lvJUYa6hHHDfAqIdhb5hI',
    appId: '1:361642844511:web:0134bcb94209b1c65116ea',
    messagingSenderId: '361642844511',
    projectId: 'reportnicdb',
    authDomain: 'reportnicdb.firebaseapp.com',
    storageBucket: 'reportnicdb.appspot.com',
    measurementId: 'G-7Z3Y1M2MP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO3MdLcdXhBRfDbFKQ4t_5MsJeKPwj2q8',
    appId: '1:361642844511:android:07e37945c6d600bf5116ea',
    messagingSenderId: '361642844511',
    projectId: 'reportnicdb',
    storageBucket: 'reportnicdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKv40OdaPqq3mfNsmpNOL5LQjNiiZT2Pc',
    appId: '1:361642844511:ios:d0eba5a2557004815116ea',
    messagingSenderId: '361642844511',
    projectId: 'reportnicdb',
    storageBucket: 'reportnicdb.appspot.com',
    iosBundleId: 'com.example.reportnic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKv40OdaPqq3mfNsmpNOL5LQjNiiZT2Pc',
    appId: '1:361642844511:ios:d0eba5a2557004815116ea',
    messagingSenderId: '361642844511',
    projectId: 'reportnicdb',
    storageBucket: 'reportnicdb.appspot.com',
    iosBundleId: 'com.example.reportnic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB07sR2b1NMI0lvJUYa6hHHDfAqIdhb5hI',
    appId: '1:361642844511:web:6d607319de5db0b05116ea',
    messagingSenderId: '361642844511',
    projectId: 'reportnicdb',
    authDomain: 'reportnicdb.firebaseapp.com',
    storageBucket: 'reportnicdb.appspot.com',
    measurementId: 'G-LDBRT8FXJ7',
  );
}
